flir_multicam:
  ros__parameters:
    cameras:
      - name: "camera0"
        serial: "25415248"
        namespace: "camera0"
        frame_id: "camera0_optical_frame"
        hardware_trigger_role: "none"
        ptp_action_role: "sender"
        force_ip_address: "192.168.100.207"
        force_ip_subnet_mask: "255.255.255.0"
        force_ip_gateway: "0.0.0.0"
      - name: "camera1"
        serial: "25415255"
        namespace: "camera1"
        frame_id: "camera1_optical_frame"
        hardware_trigger_role: "none"
        ptp_action_role: "receiver"
        force_ip_address: "192.168.100.208"
        force_ip_subnet_mask: "255.255.255.0"
        force_ip_gateway: "0.0.0.0"
      - name: "camera2"
        serial: "25415251"
        namespace: "camera2"
        frame_id: "camera2_optical_frame"
        hardware_trigger_role: "none"
        ptp_action_role: "receiver"
        force_ip_address: "192.168.100.206"
        force_ip_subnet_mask: "255.255.255.0"
        force_ip_gateway: "0.0.0.0"
